USE PlanIt
GO

DROP PROCEDURE IF EXISTS uspDeactivateUser
GO

CREATE PROCEDURE uspDeactivateUser
	@UserID AS INT
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN TRANSACTION

	UPDATE Users SET Active = 0 
	OUTPUT INSERTED.*
	WHERE UserID = @UserID
	AND Active <> 0

COMMIT TRANSACTION
GO